

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import static java.awt.event.KeyEvent.VK_ENTER;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.xml.bind.JAXBElement;
import org.docx4j.model.datastorage.migration.VariablePrepare;
import org.docx4j.openpackaging.exceptions.Docx4JException;
import org.docx4j.openpackaging.packages.WordprocessingMLPackage;
import org.docx4j.openpackaging.parts.WordprocessingML.MainDocumentPart;
import org.docx4j.wml.ContentAccessor;
import org.docx4j.wml.P;
import org.docx4j.wml.Text;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.Locale;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import java.sql.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author frank
 */
public class EasyFast extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public EasyFast() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jCBRutaNo = new javax.swing.JComboBox<>();
        jFFCedula = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jRBMasc = new javax.swing.JRadioButton();
        jRBFem = new javax.swing.JRadioButton();
        jTfNombre = new javax.swing.JTextField();
        jTFApel = new javax.swing.JTextField();
        jFFTelefFijo = new javax.swing.JFormattedTextField();
        jFFTelefCel = new javax.swing.JFormattedTextField();
        jCBEstadoCivil = new javax.swing.JComboBox<>();
        jTFNomCony = new javax.swing.JTextField();
        jFFTelefCony = new javax.swing.JFormattedTextField();
        jTFReferClient = new javax.swing.JTextField();
        jFFTelefReferClient = new javax.swing.JFormattedTextField();
        jTFDirCalle = new javax.swing.JTextField();
        jTFDirNum = new javax.swing.JTextField();
        jTFDirSect = new javax.swing.JTextField();
        jTFDirApart = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jBton_Foto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jCBTipComer = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jTFNomComer = new javax.swing.JTextField();
        jTFDirComer = new javax.swing.JTextField();
        jTF_DirNumComer = new javax.swing.JTextField();
        jFFTelefComer = new javax.swing.JFormattedTextField();
        jFFMontPrest = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jBtonCerrar = new javax.swing.JButton();
        jBtonAplicar = new javax.swing.JButton();
        jLabMontLetras = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N

        jCBRutaNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBRutaNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCBRutaNoKeyReleased(evt);
            }
        });

        try {
            jFFCedula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-#######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFFCedula.setText("118-0008311-2");
        jFFCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFFCedulaKeyPressed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexo"));

        BG1.add(jRBMasc);
        jRBMasc.setSelected(true);
        jRBMasc.setText("Masculino");
        jRBMasc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRBMascKeyPressed(evt);
            }
        });

        BG1.add(jRBFem);
        jRBFem.setText("Femenino");
        jRBFem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRBFemKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBFem)
                    .addComponent(jRBMasc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jRBMasc, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBFem, javax.swing.GroupLayout.PREFERRED_SIZE, 17, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTfNombre.setText("FRANCISCO");
        jTfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTfNombreKeyPressed(evt);
            }
        });

        jTFApel.setText("VALDEZ FERREIRA");
        jTFApel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFApelKeyPressed(evt);
            }
        });

        try {
            jFFTelefFijo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFFTelefFijo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFFTelefFijoKeyPressed(evt);
            }
        });

        try {
            jFFTelefCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFFTelefCel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFFTelefCelKeyPressed(evt);
            }
        });

        jCBEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBEstadoCivil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCBEstadoCivilKeyPressed(evt);
            }
        });

        jTFNomCony.setEnabled(false);
        jTFNomCony.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFNomConyKeyPressed(evt);
            }
        });

        try {
            jFFTelefCony.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFFTelefCony.setEnabled(false);
        jFFTelefCony.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFFTelefConyKeyPressed(evt);
            }
        });

        jTFReferClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFReferClientKeyPressed(evt);
            }
        });

        try {
            jFFTelefReferClient.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFFTelefReferClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFFTelefReferClientKeyPressed(evt);
            }
        });

        jTFDirCalle.setText("C/ La Sabana");
        jTFDirCalle.setSize(new java.awt.Dimension(80, 26));
        jTFDirCalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFDirCalleKeyPressed(evt);
            }
        });

        jTFDirNum.setText("03");
        jTFDirNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFDirNumKeyPressed(evt);
            }
        });

        jTFDirSect.setText("La Sabana");
        jTFDirSect.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFDirSectKeyPressed(evt);
            }
        });

        jTFDirApart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFDirApartKeyPressed(evt);
            }
        });

        jLabel2.setText("Nombre");

        jLabel7.setText("Apellidos");
        jLabel7.setName(""); // NOI18N

        jLabel8.setText("Estado civil");
        jLabel8.setName(""); // NOI18N

        jLabel4.setText("No. Cedula");

        jLabel9.setText("Teléf. fijo");

        jLabel10.setText("Teléf. Celular");

        jLabel11.setText("Conyugue");

        jLabel14.setText("Teléfono");

        jLabel12.setText("Referencia");

        jLabel13.setText("Teléfono");

        jLabel15.setText("Ruta No.");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );

        jBton_Foto.setText("Foto");
        jBton_Foto.setFocusable(false);

        jLabel3.setText("Calle");

        jLabel5.setText("Número");

        jLabel6.setText("Sector");

        jLabel17.setText("Apto. No.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFReferClient)
                    .addComponent(jTFDirCalle)
                    .addComponent(jTFDirSect)
                    .addComponent(jTfNombre)
                    .addComponent(jTFApel)
                    .addComponent(jFFCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBRutaNo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNomCony, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel5)
                            .addComponent(jLabel17))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFFTelefCony, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFDirNum, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFDirApart, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFFTelefReferClient, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFFTelefCel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFFTelefFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jBton_Foto)
                                .addGap(34, 34, 34)))
                        .addGap(72, 72, 72))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jFFTelefCel, jFFTelefCony, jFFTelefFijo, jFFTelefReferClient});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jFFCedula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jCBRutaNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTfNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFFTelefFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFApel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jFFTelefCel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBEstadoCivil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBton_Foto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFNomCony, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jFFTelefCony, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFReferClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jFFTelefReferClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFDirCalle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFDirNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFDirSect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFDirApart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jCBEstadoCivil, jCBRutaNo, jFFCedula, jFFTelefCel, jFFTelefCony, jFFTelefFijo, jFFTelefReferClient, jTFDirApart, jTFDirCalle, jTFDirNum, jTFDirSect, jTFNomCony, jTFReferClient});

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del préstamo"));

        jCBTipComer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBTipComer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCBTipComerKeyPressed(evt);
            }
        });

        jLabel16.setText("Tipo Comercio");
        jLabel16.setFocusable(false);

        jTFNomComer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFNomComerKeyPressed(evt);
            }
        });

        jTFDirComer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFDirComerKeyPressed(evt);
            }
        });

        jTF_DirNumComer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_DirNumComerKeyPressed(evt);
            }
        });

        try {
            jFFTelefComer.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFFTelefComer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFFTelefComerKeyPressed(evt);
            }
        });

        jFFMontPrest.setForeground(new java.awt.Color(204, 0, 0));
        jFFMontPrest.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        jFFMontPrest.setText("20000");
        jFFMontPrest.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jFFMontPrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFFMontPrestActionPerformed(evt);
            }
        });
        jFFMontPrest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFFMontPrestKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFFMontPrestKeyReleased(evt);
            }
        });

        jLabel18.setText("Nombre comercio");

        jLabel19.setText("Dirección");

        jLabel20.setText("Número");

        jLabel21.setText("Teléfono");

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel22.setText("Monto");
        jLabel22.setFocusable(false);

        jBtonCerrar.setText("Cerrar");
        jBtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtonCerrarActionPerformed(evt);
            }
        });

        jBtonAplicar.setText("Aplicar");
        jBtonAplicar.setToolTipText("");
        jBtonAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtonAplicarActionPerformed(evt);
            }
        });

        jLabMontLetras.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabMontLetras.setForeground(new java.awt.Color(255, 0, 0));
        jLabMontLetras.setText("MONTOL");
        jLabMontLetras.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel19))
                .addGap(56, 56, 56)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFNomComer, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(jCBTipComer, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFDirComer, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_DirNumComer, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFFTelefComer, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(140, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jFFMontPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabMontLetras, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtonCerrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtonAplicar)
                        .addGap(17, 17, 17))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCBTipComer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jTFNomComer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jFFTelefComer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTFDirComer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTF_DirNumComer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jFFMontPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabMontLetras)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtonCerrar)
                            .addComponent(jBtonAplicar))
                        .addGap(6, 6, 6))))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jCBTipComer, jFFTelefComer, jTFDirComer, jTFNomComer, jTF_DirNumComer});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
     
    public static String cantidadConLetra(String s) {
        StringBuilder result = new StringBuilder();
        BigDecimal totalBigDecimal = new BigDecimal(s).setScale(2, BigDecimal.ROUND_DOWN);
        long parteEntera = totalBigDecimal.toBigInteger().longValue();
        int triUnidades      = (int)((parteEntera % 1000));
        int triMiles         = (int)((parteEntera / 1000) % 1000);
        int triMillones      = (int)((parteEntera / 1000000) % 1000);
        int triMilMillones   = (int)((parteEntera / 1000000000) % 1000);
 
        if (parteEntera == 0) {
            result.append("Cero ");
            return result.toString();
        }
 
        if (triMilMillones > 0) result.append(triTexto(triMilMillones).toString() + "Mil ");
        if (triMillones > 0)    result.append(triTexto(triMillones).toString());
 
        if (triMilMillones == 0 && triMillones == 1) result.append("Millón ");
        else if (triMilMillones > 0 || triMillones > 0) result.append("Millones ");
 
        if (triMiles > 0)       result.append(triTexto(triMiles).toString() + "Mil ");
        if (triUnidades > 0)    result.append(triTexto(triUnidades).toString());
 
        return result.toString();
    }
          
    private static StringBuilder triTexto(int n) {
        StringBuilder result = new StringBuilder();
        int centenas = n / 100;
        int decenas  = (n % 100) / 10;
        int unidades = (n % 10);
 
        switch (centenas) {
            case 0: break;
            case 1:
                if (decenas == 0 && unidades == 0) {
                    result.append("Cien ");
                    return result;
                }
                else result.append("Ciento ");
                break;
            case 2: result.append("Doscientos "); break;
            case 3: result.append("Trescientos "); break;
            case 4: result.append("Cuatrocientos "); break;
            case 5: result.append("Quinientos "); break;
            case 6: result.append("Seiscientos "); break;
            case 7: result.append("Setecientos "); break;
            case 8: result.append("Ochocientos "); break;
            case 9: result.append("Novecientos "); break;
        }
 
        switch (decenas) {
            case 0: break;
            case 1:
                if (unidades == 0) { result.append("Diez "); return result; }
                else if (unidades == 1) { result.append("Once "); return result; }
                else if (unidades == 2) { result.append("Doce "); return result; }
                else if (unidades == 3) { result.append("Trece "); return result; }
                else if (unidades == 4) { result.append("Catorce "); return result; }
                else if (unidades == 5) { result.append("Quince "); return result; }
                else result.append("Dieci");
                break;
            case 2:
                if (unidades == 0) { result.append("Veinte "); return result; }
                else result.append("Veinti");
                break;
            case 3: result.append("Treinta "); break;
            case 4: result.append("Cuarenta "); break;
            case 5: result.append("Cincuenta "); break;
            case 6: result.append("Sesenta "); break;
            case 7: result.append("Setenta "); break;
            case 8: result.append("Ochenta "); break;
            case 9: result.append("Noventa "); break;
        }
 
        if (decenas > 2 && unidades > 0)
            result.append("y ");
 
        switch (unidades) {
            case 0: break;
            case 1: result.append("Un "); break;
            case 2: result.append("Dos "); break;
            case 3: result.append("Tres "); break;
            case 4: result.append("Cuatro "); break;
            case 5: result.append("Cinco "); break;
            case 6: result.append("Seis "); break;
            case 7: result.append("Siete "); break;
            case 8: result.append("Ocho "); break;
            case 9: result.append("Nueve "); break;
        }
       
        return result;
    }
         
    
    private void jBtonAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtonAplicarActionPerformed
       
        try {
            final String inPath = "/Users/frank/NetBeansProjects/EditarWord/inCont.docx"; 
            String outPath = "/Users/frank/Desktop/Pagare/" + jTfNombre.getText() + " " + jTFApel.getText().trim() + ".docx";
            
            //File archivo = selecArchivo.getSelectedFile();
            /* Claves:
            nombreDeudor = <nomdeu00> "Francisco Valdez"
            NOMBREDEUDOR = <?NOMDEU00>
            cedula = <numced00>
            
            calle = <call00> "Calle Sanchez"
            sector = <sec00> "La sabana"
            numeroCasa = <num00> "08"
            municipio = <mun00>  "Maimon"         
            provincia = <prov00> "Monseñor Nouel'
            
            deudor/a = <deu00> "deudor/deudora"
            DEUDOR/A = <?deu00>  "DEUDOR/DEUDORA"
            el/la = <art00> 
            El/LA = <?art00>
            señor/a = <gen00> "señor/señora"
            
            diaSemanaCobro = <diaSemCob00> "'dia Lunes' 17"
            diaFecha = <diaFec00> "17"
            diaFechaLetras = <!diaLetFec00> "lunes"
            diaFechaInicioPago <diaFecIniPag00>
            diaFechaLetraInicioPago <!diaFecLetIniPag00>
            MesFecha = <mesFec00> "06"
            MesFechaLetras = <!mesFec00> "junio"
            AñoFecha = <anoFec00> "2019"
            AñoFechaLetras = <!anoLetFec00> "dos mil diesinueve"
            
            montoLetras = <?!monLet00> "DOS MIL"
            montoNumeros = <monNum00> "2,000"
            montoNumerosPagar = <monNumPag00> "200"
            montoLetrasPagar = <?!monLetPag00> "DOSCIENTOS"
            numeroCuotas = <numCuo00> "13 ó 15"                                                
            numeroCuotasLetras = <!numCuoLet00> "13 ó 15"
            */
            String art = "";
            String gen = "";
            String deu = "";
            //String DEU = "";
            Calendar fecha = Calendar.getInstance();
            Locale locale = Locale.getDefault();
            String montoN = "", montoL = "", nCuotaL = "", NCuota = "13";
            String mesL = "", anoL = "";
                                                        
            final Double porc13 = 0.1, porc15 = 0.086;
            
            Double monPrest = 0.0, porc = 0.0, aCobrar = 0.0, totalP = 0.0;
            int semanas = 0, diaMes = 0, mes = 0, anio = 0;
  //         try{
               
            
            diaMes = fecha.get(Calendar.DAY_OF_MONTH);
            mes = fecha.get(Calendar.MONTH);
            anio = fecha.get(Calendar.YEAR);
            anoL = cantidadConLetra(Integer.toString(anio)).toLowerCase();
            
            switch (mes){
                 case 0: mesL = "Enero"; break;
                 case 1: mesL = "Febrero"; break;
                 case 2: mesL = "Marzo"; break;
                 case 3: mesL = "Abril"; break;
                 case 4: mesL = "Mayo"; break;
                 case 5: mesL = "Junio"; break;
                 case 6: mesL = "Julio"; break;
                 case 7: mesL = "Agosto"; break;
                 case 8: mesL = "Septiembre"; break;
                 case 9: mesL = "Octubre"; break;
                 case 10: mesL = "Noviembre"; break;
                 case 11: mesL = "Diciembre"; break;
                 default: mesL = Integer.toString(Calendar.MONTH);
             }
            
            if (!jFFMontPrest.getText().trim().isEmpty()) {            
               montoN = jFFMontPrest.getText().trim().replace(",", "");            
               montoL = cantidadConLetra(montoN).toUpperCase();
               monPrest = Double.parseDouble(jFFMontPrest.getText().replaceAll(",", ""));
            }
               semanas = Integer.parseInt(NCuota);
            
               porc = semanas*porc13;
               totalP = monPrest * porc;
               aCobrar = totalP/semanas;
            
            //jLabel18.setText(aCobrar.toString());
            if (jRBMasc.isSelected()){ art = "el"; gen = "señor"; deu = "deudor";
            } else {art = "la"; gen = "señora"; deu = "deudora";}
            
            
            nCuotaL = cantidadConLetra(NCuota);
           // WordprocessingMLPackage wordMLPackage = WordprocessingMLPackage.load(new File(archivo.getPath()));
            WordprocessingMLPackage wordMLPackage = WordprocessingMLPackage.load(new File(inPath));                        
            
            
            //wordMLPackage.getMainDocumentPart().variableReplace(mappings);
            findAndReplace(wordMLPackage, "<?NOMDEU00>", jTfNombre.getText().trim() + " " + jTFApel.getText().trim());                        
            findAndReplace(wordMLPackage, "<art00>", art); //Cambia el articulo dependiendo de su genero
            findAndReplace(wordMLPackage, "<?art00>", art.toUpperCase()); //Cambia el articulo dependiendo de su genero y a mayusculas
            findAndReplace(wordMLPackage, "<gen00>", gen); //Cambia el titulo dependiendo de su genero
            findAndReplace(wordMLPackage, "<deu00>", deu); //Cambia el titulo dependiendo de su genero
            findAndReplace(wordMLPackage, "<numced00>", jFFCedula.getText().trim()); //Numero de casa
            findAndReplace(wordMLPackage, "<call00>", jTFDirCalle.getText().trim());
            findAndReplace(wordMLPackage, "<num00>", jTFDirNum.getText().trim());
            findAndReplace(wordMLPackage, "<sec00>", jTFDirSect.getText().trim());
            
            findAndReplace(wordMLPackage, "<!mesFec00>", mesL); //Fecha del mes en letras
            
            findAndReplace(wordMLPackage, "<diaFec00>", Integer.toString(diaMes));
            
            findAndReplace(wordMLPackage, "<!anoLetFec00>", anoL);
            findAndReplace(wordMLPackage, "<anoFec00>", Integer.toString(anio));
            
            findAndReplace(wordMLPackage, "<diaFecIniPag00>", Integer.toString(diaInicioCobro(fecha.get(Calendar.YEAR), fecha.get(Calendar.WEEK_OF_YEAR))[0])); //Dia de inicio cobro. 
            findAndReplace(wordMLPackage, "<mesFec00>", Integer.toString(diaInicioCobro(fecha.get(Calendar.YEAR), fecha.get(Calendar.WEEK_OF_YEAR))[1])); //Mes de inicio cobro. 
            findAndReplace(wordMLPackage, "<anoFec00>", Integer.toString(diaInicioCobro(fecha.get(Calendar.YEAR), fecha.get(Calendar.WEEK_OF_YEAR))[2])); //Año de inicio cobro. 
            
            findAndReplace(wordMLPackage, "<?deu00>", deu.toUpperCase());
            findAndReplace(wordMLPackage, "<!diaLetFec00>", cantidadConLetra(Integer.toString(diaMes)).toLowerCase());
            
            findAndReplace(wordMLPackage, "<mun00>", "San Ignacio de Sabaneta");
            findAndReplace(wordMLPackage, "<prov00>", "Santiago Rodriguez");
            findAndReplace(wordMLPackage, "<?!monLet00>", montoL);
            findAndReplace(wordMLPackage, "<monNum00>", jFFMontPrest.getText().trim());
            findAndReplace(wordMLPackage, "<!numCuoLet00>", nCuotaL);
            findAndReplace(wordMLPackage, "<numCuo00>", NCuota);
            findAndReplace(wordMLPackage, "<?!monLetPag00>", cantidadConLetra(aCobrar.toString().toUpperCase()).toUpperCase());
            findAndReplace(wordMLPackage, "<monNumPag00>", aCobrar.toString());
            //findAndReplace(wordMLPackage, "", inPath);
            wordMLPackage.save(new File(outPath));           
// TODO add your handling code here:
        } catch (Docx4JException ex) {
            Logger.getLogger(EasyFast.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(EasyFast.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtonAplicarActionPerformed

    public static int[] diaInicioCobro(int anio, int semanaAnio){
        int[] fechasDiaMesAnio = new int[3];
        Calendar diaInicia = Calendar.getInstance();
        diaInicia.set(Calendar.YEAR, anio);
        diaInicia.set(Calendar.WEEK_OF_YEAR, semanaAnio + 1);
        diaInicia.set(Calendar.DAY_OF_WEEK, Calendar.MONDAY);
        fechasDiaMesAnio[0] = diaInicia.get(Calendar.DAY_OF_MONTH);
        fechasDiaMesAnio[1] = diaInicia.get(Calendar.MONTH);
        fechasDiaMesAnio[2] = diaInicia.get(Calendar.YEAR);
        return fechasDiaMesAnio;
    }
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
     jCBRutaNo.requestFocus();
     jCBRutaNo.removeAllItems();
     jCBRutaNo.addItem("Selecione una opción");
     jCBRutaNo.addItem("01 - Santiago Rodriguez");
     jCBRutaNo.addItem("02 - Dajabón");
     jCBRutaNo.addItem("03 - Otros");
     //jCB_RutaNo.addItem("04");
     
     jCBEstadoCivil.removeAllItems();
     jCBEstadoCivil.addItem("Seleccione una opción");
     jCBEstadoCivil.addItem("Soltero(a)");
     jCBEstadoCivil.addItem("Casado(a)");
     jCBEstadoCivil.addItem("Divorciado(a)");
     jCBEstadoCivil.addItem("Unión libre");
     jCBEstadoCivil.addItem("Viudo(a)");
     //jTF_Nombre.setText(jCBox_EstadoCivil.getItemAt(2));
     
     
     jCBTipComer.removeAllItems();
     jCBTipComer.addItem("Selecione una opción");
     jCBTipComer.addItem("Centro de uñas");
     jCBTipComer.addItem("Colmado");
     jCBTipComer.addItem("Puesto de frituras");
     //jCB_TipComer.addItem();
     
     jLabMontLetras.setVisible(false);
     
     
        
            //INCON = new File(inPath);
        
     
    }//GEN-LAST:event_formWindowOpened

    private void jBtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtonCerrarActionPerformed
        System.exit(0);
        //dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jBtonCerrarActionPerformed

    private void jFFCedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFFCedulaKeyPressed
        if((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER)) 
           jRBMasc.requestFocus();
       if((evt.getKeyCode() == KeyEvent.VK_UP))
           jCBRutaNo.requestFocus();                  
    }//GEN-LAST:event_jFFCedulaKeyPressed

    private void jFFTelefCelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFFTelefCelKeyPressed
       if((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER)) 
           jCBEstadoCivil.requestFocus();
       if((evt.getKeyCode() == KeyEvent.VK_UP))
           jFFTelefCel.requestFocus(); 
    }//GEN-LAST:event_jFFTelefCelKeyPressed

    private void jFFTelefFijoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFFTelefFijoKeyPressed
       if((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER)) 
           jFFTelefCel.requestFocus();
       if((evt.getKeyCode() == KeyEvent.VK_UP))
           jTFApel.requestFocus(); 
    }//GEN-LAST:event_jFFTelefFijoKeyPressed

    private void jFFMontPrestKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFFMontPrestKeyReleased
        if(((evt.getKeyCode() == VK_ENTER) || (jFFMontPrest.isFocusOwner()))&&(!jFFMontPrest.getText().isEmpty())){
           String n = jFFMontPrest.getText().replace(",", "");
            String v = EasyFast.cantidadConLetra(n.trim()); 
            jLabMontLetras.setText(v.toUpperCase()); 
         }
        if(!jFFMontPrest.getText().isEmpty()){
               jLabMontLetras.setVisible(true);
            } else {jLabMontLetras.setVisible(false);}         
    }//GEN-LAST:event_jFFMontPrestKeyReleased
    
    private void jRBMascKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRBMascKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DOWN){
           jRBFem.requestFocus();
        }
        if((evt.getKeyCode() == KeyEvent.VK_UP) || (evt.getKeyCode() == KeyEvent.VK_LEFT)){
           jFFCedula.requestFocus();
        }
        
        if ((evt.getKeyCode() == VK_ENTER) || (evt.getKeyCode() == KeyEvent.VK_SPACE)){
           if(jRBMasc.isFocusOwner()){
              jRBMasc.setSelected(true);
           }
           if(jRBFem.isFocusOwner()){
              jRBFem.setSelected(true);
           }
        if(evt.getKeyCode() == VK_ENTER){   
           jTfNombre.requestFocus();          
         }   
        }
    }//GEN-LAST:event_jRBMascKeyPressed

    private void jCBRutaNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCBRutaNoKeyReleased
        if(evt.getKeyCode() == VK_ENTER){
           jFFCedula.requestFocus();
        }        
    }//GEN-LAST:event_jCBRutaNoKeyReleased

    private void jRBFemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRBFemKeyPressed
       
        if ((evt.getKeyCode() == VK_ENTER) || (evt.getKeyCode() == KeyEvent.VK_SPACE)){
           if(jRBFem.isFocusOwner()){
              jRBFem.setSelected(true);
           }
           if(jRBFem.isFocusOwner()){
              jRBFem.setSelected(true);
           }
           if(((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER)) && (jRBFem.isSelected() || jRBMasc.isSelected() )){
              jTfNombre.requestFocus();    
           }         
    }//GEN-LAST:event_jRBFemKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_UP)
              jRBMasc.requestFocus();
    }
    
    private void jTfNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfNombreKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_UP) 
           if(jRBFem.isSelected()){
               jRBFem.requestFocus();
           } else jRBMasc.requestFocus();
       
       if(((evt.getKeyCode() == KeyEvent.VK_DOWN)||(evt.getKeyCode() == KeyEvent.VK_ENTER)) &&(!jTfNombre.getText().isEmpty()))
           jTFApel.requestFocus();
               
    }//GEN-LAST:event_jTfNombreKeyPressed

    private void jTFApelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFApelKeyPressed
       if((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER)) 
           jFFTelefFijo.requestFocus();
       if((evt.getKeyCode() == KeyEvent.VK_UP))
           jTfNombre.requestFocus();
    }//GEN-LAST:event_jTFApelKeyPressed

    private void jTFNomConyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNomConyKeyPressed
       if((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER)) 
           jFFTelefCony.requestFocus();
       if((evt.getKeyCode() == KeyEvent.VK_UP))
           jCBEstadoCivil.requestFocus();
    }//GEN-LAST:event_jTFNomConyKeyPressed

    private void jFFTelefConyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFFTelefConyKeyPressed
       if((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER)) 
           jTFReferClient.requestFocus();
       if((evt.getKeyCode() == KeyEvent.VK_UP))
           jTFNomCony.requestFocus(); 
    }//GEN-LAST:event_jFFTelefConyKeyPressed

    private void jTFReferClientKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFReferClientKeyPressed
       if((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER)) 
           jFFTelefReferClient.requestFocus();
       if((evt.getKeyCode() == KeyEvent.VK_UP))
           jFFTelefCony.requestFocus(); 
    }//GEN-LAST:event_jTFReferClientKeyPressed

    private void jFFTelefReferClientKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFFTelefReferClientKeyPressed
       if((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER)) 
           jTFDirCalle.requestFocus();
       if((evt.getKeyCode() == KeyEvent.VK_UP))
           jTFReferClient.requestFocus(); 
    }//GEN-LAST:event_jFFTelefReferClientKeyPressed

    private void jTFDirCalleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDirCalleKeyPressed
       if((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER)) 
           jTFDirNum.requestFocus();
       if((evt.getKeyCode() == KeyEvent.VK_UP))
           jFFTelefReferClient.requestFocus(); 
    }//GEN-LAST:event_jTFDirCalleKeyPressed

    private void jTFDirNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDirNumKeyPressed
       if((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER)) 
           jTFDirSect.requestFocus();
       if((evt.getKeyCode() == KeyEvent.VK_UP))
           jTFDirCalle.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDirNumKeyPressed

    private void jTFDirSectKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDirSectKeyPressed
       if((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER)) 
           jTFDirApart.requestFocus();
       if((evt.getKeyCode() == KeyEvent.VK_UP))
           jTFDirNum.requestFocus();
    }//GEN-LAST:event_jTFDirSectKeyPressed

    private void jTFDirApartKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDirApartKeyPressed
       if((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER)) 
           jCBTipComer.requestFocus();
       if((evt.getKeyCode() == KeyEvent.VK_UP))
           jTFDirSect.requestFocus(); 
    }//GEN-LAST:event_jTFDirApartKeyPressed

    private void jCBEstadoCivilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCBEstadoCivilKeyPressed
       if (evt.getKeyCode() == VK_ENTER){
           habilCampCony();
           if (!jTFNomCony.isEnabled())
               jTFReferClient.requestFocus();
        }  
    }//GEN-LAST:event_jCBEstadoCivilKeyPressed

    private void jCBTipComerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCBTipComerKeyPressed
       if ((evt.getKeyCode() == KeyEvent.VK_ENTER) && (0 != jCBTipComer.getSelectedIndex()))
           jTFNomComer.requestFocus();
         /*  jCB_TipComer.addActionListener(new ActionListener() {
               @Override
               public void actionPerformed(ActionEvent e) {
                   String v;
                   v = (String)jCB_TipComer.getSelectedItem();
                   if ("Fritura".equals(v));
               }
           } );*/
    }//GEN-LAST:event_jCBTipComerKeyPressed

    private void jTFNomComerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNomComerKeyPressed
       if((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER)) 
           jFFTelefComer.requestFocus();
       if((evt.getKeyCode() == KeyEvent.VK_UP))
           jCBTipComer.requestFocus(); 
    }//GEN-LAST:event_jTFNomComerKeyPressed

    private void jTFDirComerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDirComerKeyPressed
       if((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER)) 
           jTF_DirNumComer.requestFocus();
       if((evt.getKeyCode() == KeyEvent.VK_UP))
           jTFNomComer.requestFocus();  

    }//GEN-LAST:event_jTFDirComerKeyPressed

    private void jTF_DirNumComerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_DirNumComerKeyPressed
       if((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER)) 
           jFFMontPrest.requestFocus();
       if((evt.getKeyCode() == KeyEvent.VK_UP))
           jTF_DirNumComer.requestFocus();  
    }//GEN-LAST:event_jTF_DirNumComerKeyPressed

    private void jFFMontPrestKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFFMontPrestKeyPressed
       if((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER)) 
           jBtonAplicar.requestFocus();
       if((evt.getKeyCode() == KeyEvent.VK_UP))
           jFFTelefComer.requestFocus(); 
    }//GEN-LAST:event_jFFMontPrestKeyPressed

    private void jFFMontPrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFFMontPrestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFFMontPrestActionPerformed

    private void jFFTelefComerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFFTelefComerKeyPressed
       if((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_ENTER)) 
           jTFDirComer.requestFocus();
       if((evt.getKeyCode() == KeyEvent.VK_UP))
           jTFNomComer.requestFocus(); 
        // TODO add your handling code here:
    }//GEN-LAST:event_jFFTelefComerKeyPressed

   //Haailita los campos Nombre conyugue y telefono si el valor del combobox es casodo o union libre.
    private void habilCampCony(){
      if((jCBEstadoCivil.getSelectedIndex() == 2) || (jCBEstadoCivil.getSelectedIndex() == 4)){
            jTFNomCony.setEnabled(true);
            jFFTelefCony.setEnabled(true);           
            jTFNomCony.requestFocus();
        } else {
            jTFNomCony.setText("");
            jFFTelefCony.setText("");
            jTFNomCony.setEnabled(false);
            jFFTelefCony.setEnabled(false);
        }            
    }
    
    public static int ValidarCampos(JTextField jTF){
        int valor = 0;
        if (jTF.getText().equals("")){
          valor = -1;
          JOptionPane.showMessageDialog(null, "Ingrese un valor. (" + valor + ")");
          
        } else {
          valor = 1;
          JOptionPane.showMessageDialog(null, "ok (" + valor + ")");
        
        } 
        
        
        return valor;
}
    
    public static void findAndReplace(WordprocessingMLPackage doc, String toFind, String replacer){
    List<Object> paragraphs = getAllElementFromObject(doc.getMainDocumentPart(), P.class);
    for(Object par : paragraphs){
        P p = (P) par;
        List<Object> texts = getAllElementFromObject(p, Text.class);
        for(Object text : texts){
            Text t = (Text)text;
            if(t.getValue().contains(toFind)){
                t.setValue(t.getValue().replace(toFind, replacer));
            }
        }
    }
}    
     
               
 public static List<Object> getAllElementFromObject(Object obj, Class<?> toSearch) {
    List<Object> result = new ArrayList<Object>();
    if (obj instanceof JAXBElement) obj = ((JAXBElement<?>) obj).getValue();

    if (obj.getClass().equals(toSearch))
        result.add(obj);
    else if (obj instanceof ContentAccessor) {
        List<?> children = ((ContentAccessor) obj).getContent();
        for (Object child : children) {
            result.addAll(getAllElementFromObject(child, toSearch));
        }
    }
    return result;
}                   
                    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EasyFast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EasyFast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EasyFast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EasyFast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EasyFast().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BG1;
    private javax.swing.JButton jBtonAplicar;
    private javax.swing.JButton jBtonCerrar;
    private javax.swing.JButton jBton_Foto;
    private javax.swing.JComboBox<String> jCBEstadoCivil;
    private javax.swing.JComboBox<String> jCBRutaNo;
    private javax.swing.JComboBox<String> jCBTipComer;
    private javax.swing.JFormattedTextField jFFCedula;
    private javax.swing.JFormattedTextField jFFMontPrest;
    private javax.swing.JFormattedTextField jFFTelefCel;
    private javax.swing.JFormattedTextField jFFTelefComer;
    private javax.swing.JFormattedTextField jFFTelefCony;
    private javax.swing.JFormattedTextField jFFTelefFijo;
    private javax.swing.JFormattedTextField jFFTelefReferClient;
    private javax.swing.JLabel jLabMontLetras;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRBFem;
    private javax.swing.JRadioButton jRBMasc;
    private javax.swing.JTextField jTFApel;
    private javax.swing.JTextField jTFDirApart;
    private javax.swing.JTextField jTFDirCalle;
    private javax.swing.JTextField jTFDirComer;
    private javax.swing.JTextField jTFDirNum;
    private javax.swing.JTextField jTFDirSect;
    private javax.swing.JTextField jTFNomComer;
    private javax.swing.JTextField jTFNomCony;
    private javax.swing.JTextField jTFReferClient;
    private javax.swing.JTextField jTF_DirNumComer;
    private javax.swing.JTextField jTfNombre;
    // End of variables declaration//GEN-END:variables

    


  
}
